services:
  orbslam2:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /home/mykola/datasets/:/datasets
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    command: /bin/bash
